### ISSUE TITLE
audit

### ISSUE THREAD

**Issue by hayashi-ay** [DeFiGeek-Community/merkle-airdrop-tool#1]
safeMathを使わないとオーバーフローの可能性がありそう。
https://github.com/DeFiGeek-Community/merkle-airdrop-tool/blob/d5a5fe71448bcce6c489f5b6b99cf7cee91e67d3/packages/contract/contracts/MerkleAirdrop.sol#L61

**Comment by 0xHaku** [comment]
solidity 0.8以上はsafemathがデフォルトで対応されているのでその可能性はない認識です
（https://ethereum.stackexchange.com/questions/91367/is-the-safemath-library-obsolete-in-solidity-0-8-0）
この箇所にのみ、その懸念があるということでしょうか？

**Comment by hayashi-ay** [comment]
なるほど。知らなかったです。大丈夫です。
