### ISSUE TITLE
一部のトークンの扱いについて

### ISSUE THREAD

**Issue by YosukeMiyata** [DeFiGeek-Community/merkle-airdrop-tool#2]
一部のトークン（USDTやL199など）は、承認されたトークンの量が0、または、追加したいトークンの量が0でないと、
approve関数が元に戻される仕様になっています。
distributorがそれらのトークンを登録、デポジットした際、現状のコードですと不具合が発生してしまいます。
https://github.com/code-423n4/2022-04-backd-findings/issues/215

例えば、アリスが登録時に50USDTをデポジットした場合、
allowanceは0、追加したい量は50となり、片方が0なので、approve関数が正常に機能します。
が、アリスがaddAirdropTokenAmount関数を使用して、10USDTを追加しようとすると、
allowanceは50、追加したい量が10となり、どちらかが0でないので、requireチェックで元に戻されてしまいます。

このようなトークンも取り扱えるように、addAirdropTokenAmount関数を以下のように、修正することをおすすめします。
```solidity
function addAirdropTokenAmount(bytes32 name, uint256 amount)
    external
    airdropInfoExist(name)
{
    address token = airdopInfos[name].token;
    IERC20(token).approve(address(this), 0); //　←追加
    IERC20(token).approve(address(this), amount);
    IERC20(token).safeTransferFrom(msg.sender, address(this), amount);
    airdopInfos[name].depositedAmount += amount;
    airdopInfos[name].stockAmount += amount;
}
```
ちなみに、先日のコードの46行目で、一部誤ったコメントを書いてしまいました。
正しくは以下になります。すみません。
/// @audit (0)との比較はアセンブリを使用するとガス代を抑えられます！
/// 例）Xがゼロでない時、revertする。
/// assembly { if iszero(iszero(X)) { revert(0, 0) } }
/// 例）Xがゼロの時、revertする。
/// assembly { if iszero(X) { revert(0, 0) } }

**Comment by 0xHaku** [comment]
事象について把握しました
同じトークンで2回目以降にregistするときも同じ対応が必要ですよね
ただこれはERC20標準実装ではないので、攻撃点になりえないことも考慮してコストを考えるなら不採用かなと思います
revertされる以上の不利益があるのであれば教えていただきたいです

**Comment by YosukeMiyata** [comment]
>  revertされる以上の不利益があるのであれば教えていただきたいです

多分ないと思います！
全体を通して、資金が流出するような深刻なバグは見つかりませんでした！
さすがハクさんです！
